// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_mxVTbhLqGc5iHN2a3fw38AbC37ISqRo',
    appId: '1:167553931562:web:6e04331d2f5d06f5726653',
    messagingSenderId: '167553931562',
    projectId: 'reelotik3336',
    authDomain: 'reelotik3336.firebaseapp.com',
    storageBucket: 'reelotik3336.firebasestorage.app',
    measurementId: 'G-QELK7XEBDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3o3W5YF61eB1VFWAwDoxDUknUKKH9o0I',
    appId: '1:167553931562:android:f82f5b95cf12823d726653',
    messagingSenderId: '167553931562',
    projectId: 'reelotik3336',
    storageBucket: 'reelotik3336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAviAMkyrUHpRHPJ6gQL6wCreAuuoi1TcI',
    appId: '1:167553931562:ios:97ac8a164af1fe09726653',
    messagingSenderId: '167553931562',
    projectId: 'reelotik3336',
    storageBucket: 'reelotik3336.firebasestorage.app',
    iosBundleId: 'com.example.reelotik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAviAMkyrUHpRHPJ6gQL6wCreAuuoi1TcI',
    appId: '1:167553931562:ios:97ac8a164af1fe09726653',
    messagingSenderId: '167553931562',
    projectId: 'reelotik3336',
    storageBucket: 'reelotik3336.firebasestorage.app',
    iosBundleId: 'com.example.reelotik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_mxVTbhLqGc5iHN2a3fw38AbC37ISqRo',
    appId: '1:167553931562:web:4ef79a3a04141719726653',
    messagingSenderId: '167553931562',
    projectId: 'reelotik3336',
    authDomain: 'reelotik3336.firebaseapp.com',
    storageBucket: 'reelotik3336.firebasestorage.app',
    measurementId: 'G-0JVBRNRTBP',
  );
}
